# Generated by Django 5.2.8 on 2025-12-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_category_alter_author_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=60, unique=True)),
                ('about', models.TextField()),
                ('pubish_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.category')),
            ],
        ),
    ]
