# Generated by Django 5.2.8 on 2025-12-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubish_date',
            new_name='publish_date',
        ),
    ]
