# Generated by Django 5.2.8 on 2025-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_pubish_date_book_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='books/coverpage.jpg', upload_to='books'),
        ),
    ]
